server: # REST and WS server
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "deezcord_password"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: false
      local: false
    bufferDurationMs: 250 # The duration of the NAS buffer. Higher values fare better against longer GC pauses
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    youtubePlaylistLoadLimit: 1 # Number of pages at 100 each
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: HIGH # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: false
    gc-warnings: true
#    ratelimit: # 
#      ipBlocks: ["ipv6/64", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
#      strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
#      searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
#      retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
      #email: "" # Email of Google account
      #password: "" # Password of Google account
    #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
      #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
      #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
      #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
      #proxyPassword: "" # Password for basic authentication

  plugins:
    - dependency: "me.rohank05:lavalink-filter-plugin:0.0.1" # replace x.x.x with the latest release tag!
      repository: "https://jitpack.io"
    - dependency: "com.github.TopiSenpai.LavaSrc:lavasrc-plugin:3.0.6"
      repository: "https://jitpack.io"

plugins:
  lavasrc:
    providers:
      - "dzisrc:%ISRC%"
      - "dzsearch:%QUERY%"
      - "scsearch:%QUERY%"
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: false
      applemusic: false
      deezer: true
    deezer:
      masterDecryptionKey: "getitsomehow-use-google"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 1
    max-size: 10MB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO

 
